<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Countries;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Countries::insert(array(
          array('id' => '1','name' => 'Afghanistan','sortname' => 'AF','phonecode' => '93'),
          array('id' => '2','name' => 'Albania','sortname' => 'AL','phonecode' => '355'),
          array('id' => '3','name' => 'Algeria','sortname' => 'DZ','phonecode' => '213'),
          array('id' => '4','name' => 'American Samoa','sortname' => 'AS','phonecode' => '1684'),
          array('id' => '5','name' => 'Andorra','sortname' => 'AD','phonecode' => '376'),
          array('id' => '6','name' => 'Angola','sortname' => 'AO','phonecode' => '244'),
          array('id' => '7','name' => 'Anguilla','sortname' => 'AI','phonecode' => '1264'),
          array('id' => '8','name' => 'Antarctica','sortname' => 'AQ','phonecode' => '0'),
          array('id' => '9','name' => 'Antigua And Barbuda','sortname' => 'AG','phonecode' => '1268'),
          array('id' => '10','name' => 'Argentina','sortname' => 'AR','phonecode' => '54'),
          array('id' => '11','name' => 'Armenia','sortname' => 'AM','phonecode' => '374'),
          array('id' => '12','name' => 'Aruba','sortname' => 'AW','phonecode' => '297'),
          array('id' => '13','name' => 'Australia','sortname' => 'AU','phonecode' => '61'),
          array('id' => '14','name' => 'Austria','sortname' => 'AT','phonecode' => '43'),
          array('id' => '15','name' => 'Azerbaijan','sortname' => 'AZ','phonecode' => '994'),
          array('id' => '16','name' => 'Bahamas The','sortname' => 'BS','phonecode' => '1242'),
          array('id' => '17','name' => 'Bahrain','sortname' => 'BH','phonecode' => '973'),
          array('id' => '18','name' => 'Bangladesh','sortname' => 'BD','phonecode' => '880'),
          array('id' => '19','name' => 'Barbados','sortname' => 'BB','phonecode' => '1246'),
          array('id' => '20','name' => 'Belarus','sortname' => 'BY','phonecode' => '375'),
          array('id' => '21','name' => 'Belgium','sortname' => 'BE','phonecode' => '32'),
          array('id' => '22','name' => 'Belize','sortname' => 'BZ','phonecode' => '501'),
          array('id' => '23','name' => 'Benin','sortname' => 'BJ','phonecode' => '229'),
          array('id' => '24','name' => 'Bermuda','sortname' => 'BM','phonecode' => '1441'),
          array('id' => '25','name' => 'Bhutan','sortname' => 'BT','phonecode' => '975'),
          array('id' => '26','name' => 'Bolivia','sortname' => 'BO','phonecode' => '591'),
          array('id' => '27','name' => 'Bosnia and Herzegovina','sortname' => 'BA','phonecode' => '387'),
          array('id' => '28','name' => 'Botswana','sortname' => 'BW','phonecode' => '267'),
          array('id' => '29','name' => 'Bouvet Island','sortname' => 'BV','phonecode' => '0'),
          array('id' => '30','name' => 'Brazil','sortname' => 'BR','phonecode' => '55'),
          array('id' => '31','name' => 'British Indian Ocean Territory','sortname' => 'IO','phonecode' => '246'),
          array('id' => '32','name' => 'Brunei','sortname' => 'BN','phonecode' => '673'),
          array('id' => '33','name' => 'Bulgaria','sortname' => 'BG','phonecode' => '359'),
          array('id' => '34','name' => 'Burkina Faso','sortname' => 'BF','phonecode' => '226'),
          array('id' => '35','name' => 'Burundi','sortname' => 'BI','phonecode' => '257'),
          array('id' => '36','name' => 'Cambodia','sortname' => 'KH','phonecode' => '855'),
          array('id' => '37','name' => 'Cameroon','sortname' => 'CM','phonecode' => '237'),
          array('id' => '38','name' => 'Canada','sortname' => 'CA','phonecode' => '1'),
          array('id' => '39','name' => 'Cape Verde','sortname' => 'CV','phonecode' => '238'),
          array('id' => '40','name' => 'Cayman Islands','sortname' => 'KY','phonecode' => '1345'),
          array('id' => '41','name' => 'Central African Republic','sortname' => 'CF','phonecode' => '236'),
          array('id' => '42','name' => 'Chad','sortname' => 'TD','phonecode' => '235'),
          array('id' => '43','name' => 'Chile','sortname' => 'CL','phonecode' => '56'),
          array('id' => '44','name' => 'China','sortname' => 'CN','phonecode' => '86'),
          array('id' => '45','name' => 'Christmas Island','sortname' => 'CX','phonecode' => '61'),
          array('id' => '46','name' => 'Cocos (Keeling) Islands','sortname' => 'CC','phonecode' => '672'),
          array('id' => '47','name' => 'Colombia','sortname' => 'CO','phonecode' => '57'),
          array('id' => '48','name' => 'Comoros','sortname' => 'KM','phonecode' => '269'),
          array('id' => '49','name' => 'Republic Of The Congo','sortname' => 'CG','phonecode' => '242'),
          array('id' => '50','name' => 'Democratic Republic Of The Congo','sortname' => 'CD','phonecode' => '242'),
          array('id' => '51','name' => 'Cook Islands','sortname' => 'CK','phonecode' => '682'),
          array('id' => '52','name' => 'Costa Rica','sortname' => 'CR','phonecode' => '506'),
          array('id' => '53','name' => 'Cote D\'Ivoire (Ivory Coast)','sortname' => 'CI','phonecode' => '225'),
          array('id' => '54','name' => 'Croatia (Hrvatska)','sortname' => 'HR','phonecode' => '385'),
          array('id' => '55','name' => 'Cuba','sortname' => 'CU','phonecode' => '53'),
          array('id' => '56','name' => 'Cyprus','sortname' => 'CY','phonecode' => '357'),
          array('id' => '57','name' => 'Czech Republic','sortname' => 'CZ','phonecode' => '420'),
          array('id' => '58','name' => 'Denmark','sortname' => 'DK','phonecode' => '45'),
          array('id' => '59','name' => 'Djibouti','sortname' => 'DJ','phonecode' => '253'),
          array('id' => '60','name' => 'Dominica','sortname' => 'DM','phonecode' => '1767'),
          array('id' => '61','name' => 'Dominican Republic','sortname' => 'DO','phonecode' => '1809'),
          array('id' => '62','name' => 'East Timor','sortname' => 'TP','phonecode' => '670'),
          array('id' => '63','name' => 'Ecuador','sortname' => 'EC','phonecode' => '593'),
          array('id' => '64','name' => 'Egypt','sortname' => 'EG','phonecode' => '20'),
          array('id' => '65','name' => 'El Salvador','sortname' => 'SV','phonecode' => '503'),
          array('id' => '66','name' => 'Equatorial Guinea','sortname' => 'GQ','phonecode' => '240'),
          array('id' => '67','name' => 'Eritrea','sortname' => 'ER','phonecode' => '291'),
          array('id' => '68','name' => 'Estonia','sortname' => 'EE','phonecode' => '372'),
          array('id' => '69','name' => 'Ethiopia','sortname' => 'ET','phonecode' => '251'),
          array('id' => '70','name' => 'External Territories of Australia','sortname' => 'XA','phonecode' => '61'),
          array('id' => '71','name' => 'Falkland Islands','sortname' => 'FK','phonecode' => '500'),
          array('id' => '72','name' => 'Faroe Islands','sortname' => 'FO','phonecode' => '298'),
          array('id' => '73','name' => 'Fiji Islands','sortname' => 'FJ','phonecode' => '679'),
          array('id' => '74','name' => 'Finland','sortname' => 'FI','phonecode' => '358'),
          array('id' => '75','name' => 'France','sortname' => 'FR','phonecode' => '33'),
          array('id' => '76','name' => 'French Guiana','sortname' => 'GF','phonecode' => '594'),
          array('id' => '77','name' => 'French Polynesia','sortname' => 'PF','phonecode' => '689'),
          array('id' => '78','name' => 'French Southern Territories','sortname' => 'TF','phonecode' => '0'),
          array('id' => '79','name' => 'Gabon','sortname' => 'GA','phonecode' => '241'),
          array('id' => '80','name' => 'Gambia The','sortname' => 'GM','phonecode' => '220'),
          array('id' => '81','name' => 'Georgia','sortname' => 'GE','phonecode' => '995'),
          array('id' => '82','name' => 'Germany','sortname' => 'DE','phonecode' => '49'),
          array('id' => '83','name' => 'Ghana','sortname' => 'GH','phonecode' => '233'),
          array('id' => '84','name' => 'Gibraltar','sortname' => 'GI','phonecode' => '350'),
          array('id' => '85','name' => 'Greece','sortname' => 'GR','phonecode' => '30'),
          array('id' => '86','name' => 'Greenland','sortname' => 'GL','phonecode' => '299'),
          array('id' => '87','name' => 'Grenada','sortname' => 'GD','phonecode' => '1473'),
          array('id' => '88','name' => 'Guadeloupe','sortname' => 'GP','phonecode' => '590'),
          array('id' => '89','name' => 'Guam','sortname' => 'GU','phonecode' => '1671'),
          array('id' => '90','name' => 'Guatemala','sortname' => 'GT','phonecode' => '502'),
          array('id' => '91','name' => 'Guernsey and Alderney','sortname' => 'XU','phonecode' => '44'),
          array('id' => '92','name' => 'Guinea','sortname' => 'GN','phonecode' => '224'),
          array('id' => '93','name' => 'Guinea-Bissau','sortname' => 'GW','phonecode' => '245'),
          array('id' => '94','name' => 'Guyana','sortname' => 'GY','phonecode' => '592'),
          array('id' => '95','name' => 'Haiti','sortname' => 'HT','phonecode' => '509'),
          array('id' => '96','name' => 'Heard and McDonald Islands','sortname' => 'HM','phonecode' => '0'),
          array('id' => '97','name' => 'Honduras','sortname' => 'HN','phonecode' => '504'),
          array('id' => '98','name' => 'Hong Kong S.A.R.','sortname' => 'HK','phonecode' => '852'),
          array('id' => '99','name' => 'Hungary','sortname' => 'HU','phonecode' => '36'),
          array('id' => '100','name' => 'Iceland','sortname' => 'IS','phonecode' => '354'),
          array('id' => '101','name' => 'India','sortname' => 'IN','phonecode' => '91'),
          array('id' => '102','name' => 'Indonesia','sortname' => 'ID','phonecode' => '62'),
          array('id' => '103','name' => 'Iran','sortname' => 'IR','phonecode' => '98'),
          array('id' => '104','name' => 'Iraq','sortname' => 'IQ','phonecode' => '964'),
          array('id' => '105','name' => 'Ireland','sortname' => 'IE','phonecode' => '353'),
          array('id' => '106','name' => 'Israel','sortname' => 'IL','phonecode' => '972'),
          array('id' => '107','name' => 'Italy','sortname' => 'IT','phonecode' => '39'),
          array('id' => '108','name' => 'Jamaica','sortname' => 'JM','phonecode' => '1876'),
          array('id' => '109','name' => 'Japan','sortname' => 'JP','phonecode' => '81'),
          array('id' => '110','name' => 'Jersey','sortname' => 'XJ','phonecode' => '44'),
          array('id' => '111','name' => 'Jordan','sortname' => 'JO','phonecode' => '962'),
          array('id' => '112','name' => 'Kazakhstan','sortname' => 'KZ','phonecode' => '7'),
          array('id' => '113','name' => 'Kenya','sortname' => 'KE','phonecode' => '254'),
          array('id' => '114','name' => 'Kiribati','sortname' => 'KI','phonecode' => '686'),
          array('id' => '115','name' => 'Korea North','sortname' => 'KP','phonecode' => '850'),
          array('id' => '116','name' => 'Korea South','sortname' => 'KR','phonecode' => '82'),
          array('id' => '117','name' => 'Kuwait','sortname' => 'KW','phonecode' => '965'),
          array('id' => '118','name' => 'Kyrgyzstan','sortname' => 'KG','phonecode' => '996'),
          array('id' => '119','name' => 'Laos','sortname' => 'LA','phonecode' => '856'),
          array('id' => '120','name' => 'Latvia','sortname' => 'LV','phonecode' => '371'),
          array('id' => '121','name' => 'Lebanon','sortname' => 'LB','phonecode' => '961'),
          array('id' => '122','name' => 'Lesotho','sortname' => 'LS','phonecode' => '266'),
          array('id' => '123','name' => 'Liberia','sortname' => 'LR','phonecode' => '231'),
          array('id' => '124','name' => 'Libya','sortname' => 'LY','phonecode' => '218'),
          array('id' => '125','name' => 'Liechtenstein','sortname' => 'LI','phonecode' => '423'),
          array('id' => '126','name' => 'Lithuania','sortname' => 'LT','phonecode' => '370'),
          array('id' => '127','name' => 'Luxembourg','sortname' => 'LU','phonecode' => '352'),
          array('id' => '128','name' => 'Macau S.A.R.','sortname' => 'MO','phonecode' => '853'),
          array('id' => '129','name' => 'Macedonia','sortname' => 'MK','phonecode' => '389'),
          array('id' => '130','name' => 'Madagascar','sortname' => 'MG','phonecode' => '261'),
          array('id' => '131','name' => 'Malawi','sortname' => 'MW','phonecode' => '265'),
          array('id' => '132','name' => 'Malaysia','sortname' => 'MY','phonecode' => '60'),
          array('id' => '133','name' => 'Maldives','sortname' => 'MV','phonecode' => '960'),
          array('id' => '134','name' => 'Mali','sortname' => 'ML','phonecode' => '223'),
          array('id' => '135','name' => 'Malta','sortname' => 'MT','phonecode' => '356'),
          array('id' => '136','name' => 'Man (Isle of)','sortname' => 'XM','phonecode' => '44'),
          array('id' => '137','name' => 'Marshall Islands','sortname' => 'MH','phonecode' => '692'),
          array('id' => '138','name' => 'Martinique','sortname' => 'MQ','phonecode' => '596'),
          array('id' => '139','name' => 'Mauritania','sortname' => 'MR','phonecode' => '222'),
          array('id' => '140','name' => 'Mauritius','sortname' => 'MU','phonecode' => '230'),
          array('id' => '141','name' => 'Mayotte','sortname' => 'YT','phonecode' => '269'),
          array('id' => '142','name' => 'Mexico','sortname' => 'MX','phonecode' => '52'),
          array('id' => '143','name' => 'Micronesia','sortname' => 'FM','phonecode' => '691'),
          array('id' => '144','name' => 'Moldova','sortname' => 'MD','phonecode' => '373'),
          array('id' => '145','name' => 'Monaco','sortname' => 'MC','phonecode' => '377'),
          array('id' => '146','name' => 'Mongolia','sortname' => 'MN','phonecode' => '976'),
          array('id' => '147','name' => 'Montserrat','sortname' => 'MS','phonecode' => '1664'),
          array('id' => '148','name' => 'Morocco','sortname' => 'MA','phonecode' => '212'),
          array('id' => '149','name' => 'Mozambique','sortname' => 'MZ','phonecode' => '258'),
          array('id' => '150','name' => 'Myanmar','sortname' => 'MM','phonecode' => '95'),
          array('id' => '151','name' => 'Namibia','sortname' => 'NA','phonecode' => '264'),
          array('id' => '152','name' => 'Nauru','sortname' => 'NR','phonecode' => '674'),
          array('id' => '153','name' => 'Nepal','sortname' => 'NP','phonecode' => '977'),
          array('id' => '154','name' => 'Netherlands Antilles','sortname' => 'AN','phonecode' => '599'),
          array('id' => '155','name' => 'Netherlands The','sortname' => 'NL','phonecode' => '31'),
          array('id' => '156','name' => 'New Caledonia','sortname' => 'NC','phonecode' => '687'),
          array('id' => '157','name' => 'New Zealand','sortname' => 'NZ','phonecode' => '64'),
          array('id' => '158','name' => 'Nicaragua','sortname' => 'NI','phonecode' => '505'),
          array('id' => '159','name' => 'Niger','sortname' => 'NE','phonecode' => '227'),
          array('id' => '160','name' => 'Nigeria','sortname' => 'NG','phonecode' => '234'),
          array('id' => '161','name' => 'Niue','sortname' => 'NU','phonecode' => '683'),
          array('id' => '162','name' => 'Norfolk Island','sortname' => 'NF','phonecode' => '672'),
          array('id' => '163','name' => 'Northern Mariana Islands','sortname' => 'MP','phonecode' => '1670'),
          array('id' => '164','name' => 'Norway','sortname' => 'NO','phonecode' => '47'),
          array('id' => '165','name' => 'Oman','sortname' => 'OM','phonecode' => '968'),
          array('id' => '166','name' => 'Pakistan','sortname' => 'PK','phonecode' => '92'),
          array('id' => '167','name' => 'Palau','sortname' => 'PW','phonecode' => '680'),
          array('id' => '168','name' => 'Palestinian Territory Occupied','sortname' => 'PS','phonecode' => '970'),
          array('id' => '169','name' => 'Panama','sortname' => 'PA','phonecode' => '507'),
          array('id' => '170','name' => 'Papua new Guinea','sortname' => 'PG','phonecode' => '675'),
          array('id' => '171','name' => 'Paraguay','sortname' => 'PY','phonecode' => '595'),
          array('id' => '172','name' => 'Peru','sortname' => 'PE','phonecode' => '51'),
          array('id' => '173','name' => 'Philippines','sortname' => 'PH','phonecode' => '63'),
          array('id' => '174','name' => 'Pitcairn Island','sortname' => 'PN','phonecode' => '0'),
          array('id' => '175','name' => 'Poland','sortname' => 'PL','phonecode' => '48'),
          array('id' => '176','name' => 'Portugal','sortname' => 'PT','phonecode' => '351'),
          array('id' => '177','name' => 'Puerto Rico','sortname' => 'PR','phonecode' => '1787'),
          array('id' => '178','name' => 'Qatar','sortname' => 'QA','phonecode' => '974'),
          array('id' => '179','name' => 'Reunion','sortname' => 'RE','phonecode' => '262'),
          array('id' => '180','name' => 'Romania','sortname' => 'RO','phonecode' => '40'),
          array('id' => '181','name' => 'Russia','sortname' => 'RU','phonecode' => '70'),
          array('id' => '182','name' => 'Rwanda','sortname' => 'RW','phonecode' => '250'),
          array('id' => '183','name' => 'Saint Helena','sortname' => 'SH','phonecode' => '290'),
          array('id' => '184','name' => 'Saint Kitts And Nevis','sortname' => 'KN','phonecode' => '1869'),
          array('id' => '185','name' => 'Saint Lucia','sortname' => 'LC','phonecode' => '1758'),
          array('id' => '186','name' => 'Saint Pierre and Miquelon','sortname' => 'PM','phonecode' => '508'),
          array('id' => '187','name' => 'Saint Vincent And The Grenadines','sortname' => 'VC','phonecode' => '1784'),
          array('id' => '188','name' => 'Samoa','sortname' => 'WS','phonecode' => '684'),
          array('id' => '189','name' => 'San Marino','sortname' => 'SM','phonecode' => '378'),
          array('id' => '190','name' => 'Sao Tome and Principe','sortname' => 'ST','phonecode' => '239'),
          array('id' => '191','name' => 'Saudi Arabia','sortname' => 'SA','phonecode' => '966'),
          array('id' => '192','name' => 'Senegal','sortname' => 'SN','phonecode' => '221'),
          array('id' => '193','name' => 'Serbia','sortname' => 'RS','phonecode' => '381'),
          array('id' => '194','name' => 'Seychelles','sortname' => 'SC','phonecode' => '248'),
          array('id' => '195','name' => 'Sierra Leone','sortname' => 'SL','phonecode' => '232'),
          array('id' => '196','name' => 'Singapore','sortname' => 'SG','phonecode' => '65'),
          array('id' => '197','name' => 'Slovakia','sortname' => 'SK','phonecode' => '421'),
          array('id' => '198','name' => 'Slovenia','sortname' => 'SI','phonecode' => '386'),
          array('id' => '199','name' => 'Smaller Territories of the UK','sortname' => 'XG','phonecode' => '44'),
          array('id' => '200','name' => 'Solomon Islands','sortname' => 'SB','phonecode' => '677'),
          array('id' => '201','name' => 'Somalia','sortname' => 'SO','phonecode' => '252'),
          array('id' => '202','name' => 'South Africa','sortname' => 'ZA','phonecode' => '27'),
          array('id' => '203','name' => 'South Georgia','sortname' => 'GS','phonecode' => '0'),
          array('id' => '204','name' => 'South Sudan','sortname' => 'SS','phonecode' => '211'),
          array('id' => '205','name' => 'Spain','sortname' => 'ES','phonecode' => '34'),
          array('id' => '206','name' => 'Sri Lanka','sortname' => 'LK','phonecode' => '94'),
          array('id' => '207','name' => 'Sudan','sortname' => 'SD','phonecode' => '249'),
          array('id' => '208','name' => 'Suriname','sortname' => 'SR','phonecode' => '597'),
          array('id' => '209','name' => 'Svalbard And Jan Mayen Islands','sortname' => 'SJ','phonecode' => '47'),
          array('id' => '210','name' => 'Swaziland','sortname' => 'SZ','phonecode' => '268'),
          array('id' => '211','name' => 'Sweden','sortname' => 'SE','phonecode' => '46'),
          array('id' => '212','name' => 'Switzerland','sortname' => 'CH','phonecode' => '41'),
          array('id' => '213','name' => 'Syria','sortname' => 'SY','phonecode' => '963'),
          array('id' => '214','name' => 'Taiwan','sortname' => 'TW','phonecode' => '886'),
          array('id' => '215','name' => 'Tajikistan','sortname' => 'TJ','phonecode' => '992'),
          array('id' => '216','name' => 'Tanzania','sortname' => 'TZ','phonecode' => '255'),
          array('id' => '217','name' => 'Thailand','sortname' => 'TH','phonecode' => '66'),
          array('id' => '218','name' => 'Togo','sortname' => 'TG','phonecode' => '228'),
          array('id' => '219','name' => 'Tokelau','sortname' => 'TK','phonecode' => '690'),
          array('id' => '220','name' => 'Tonga','sortname' => 'TO','phonecode' => '676'),
          array('id' => '221','name' => 'Trinidad And Tobago','sortname' => 'TT','phonecode' => '1868'),
          array('id' => '222','name' => 'Tunisia','sortname' => 'TN','phonecode' => '216'),
          array('id' => '223','name' => 'Turkey','sortname' => 'TR','phonecode' => '90'),
          array('id' => '224','name' => 'Turkmenistan','sortname' => 'TM','phonecode' => '7370'),
          array('id' => '225','name' => 'Turks And Caicos Islands','sortname' => 'TC','phonecode' => '1649'),
          array('id' => '226','name' => 'Tuvalu','sortname' => 'TV','phonecode' => '688'),
          array('id' => '227','name' => 'Uganda','sortname' => 'UG','phonecode' => '256'),
          array('id' => '228','name' => 'Ukraine','sortname' => 'UA','phonecode' => '380'),
          array('id' => '229','name' => 'United Arab Emirates','sortname' => 'AE','phonecode' => '971'),
          array('id' => '230','name' => 'United Kingdom','sortname' => 'GB','phonecode' => '44'),
          array('id' => '231','name' => 'United States','sortname' => 'US','phonecode' => '1'),
          array('id' => '232','name' => 'United States Minor Outlying Islands','sortname' => 'UM','phonecode' => '1'),
          array('id' => '233','name' => 'Uruguay','sortname' => 'UY','phonecode' => '598'),
          array('id' => '234','name' => 'Uzbekistan','sortname' => 'UZ','phonecode' => '998'),
          array('id' => '235','name' => 'Vanuatu','sortname' => 'VU','phonecode' => '678'),
          array('id' => '236','name' => 'Vatican City State (Holy See)','sortname' => 'VA','phonecode' => '39'),
          array('id' => '237','name' => 'Venezuela','sortname' => 'VE','phonecode' => '58'),
          array('id' => '238','name' => 'Vietnam','sortname' => 'VN','phonecode' => '84'),
          array('id' => '239','name' => 'Virgin Islands (British)','sortname' => 'VG','phonecode' => '1284'),
          array('id' => '240','name' => 'Virgin Islands (US)','sortname' => 'VI','phonecode' => '1340'),
          array('id' => '241','name' => 'Wallis And Futuna Islands','sortname' => 'WF','phonecode' => '681'),
          array('id' => '242','name' => 'Western Sahara','sortname' => 'EH','phonecode' => '212'),
          array('id' => '243','name' => 'Yemen','sortname' => 'YE','phonecode' => '967'),
          array('id' => '244','name' => 'Yugoslavia','sortname' => 'YU','phonecode' => '38'),
          array('id' => '245','name' => 'Zambia','sortname' => 'ZM','phonecode' => '260'),
          array('id' => '246','name' => 'Zimbabwe','sortname' => 'ZW','phonecode' => '263')
        ));
    }
}
